apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: hello-arc
  namespace: prod
spec:
  releaseName: hello-arc-prod
  chart:
    git: https://github.com/mdrakiburrahman/hello_arc.git
    path: charts/hello-arc
    ref: master
  values:
    image:
      repository: liorkamrat/hello-arc
      tag: latest
    replicaCount: 2
    env:
      name: MESSAGE
      value: Blender goes burr burrrrr!
